//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Method_Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchData
    {
        public int Id { get; set; }
        public string path { get; set; }
        public string filename { get; set; }
    }
}
